23/Dec/2015 11:20:53 INFO get_folder "inner" took: 4.84867017257e-05 seconds
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:20:53 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:20:53 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:20:53 INFO Power On: True
23/Dec/2015 11:20:53 INFO Power On: True
23/Dec/2015 11:20:53 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:20:53 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:20:53 INFO Datastore: datastore
23/Dec/2015 11:20:53 INFO Datastore: datastore
23/Dec/2015 11:20:53 INFO Connecting to: <Mock name='mock.connection_details().host' id='53511824'>, As: <Mock name='mock.connection_details().username' id='58559728'>, Pwd: <Mock name='mock.connection_details().password' id='58559632'>, Port: <Mock name='mock.connection_details().port' id='58558768'>
23/Dec/2015 11:20:53 INFO Connecting to: <Mock name='mock.connection_details().host' id='53511824'>, As: <Mock name='mock.connection_details().username' id='58559728'>, Pwd: <Mock name='mock.connection_details().password' id='58559632'>, Port: <Mock name='mock.connection_details().port' id='58558768'>
23/Dec/2015 11:20:53 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='55679888'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='55677968'>
23/Dec/2015 11:20:53 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='55679888'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='55677968'>
23/Dec/2015 11:20:53 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:20:53 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:21:19 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='54849616'>:<Mock name='mock.get_connection_details().port' id='54851184'>' User: '<Mock name='mock.get_connection_details().user' id='54851120'>' Reason: TEST Exception
23/Dec/2015 11:21:19 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='54849616'>:<Mock name='mock.get_connection_details().port' id='54851184'>' User: '<Mock name='mock.get_connection_details().user' id='54851120'>' Reason: TEST Exception
23/Dec/2015 11:21:19 INFO cloning VM...
23/Dec/2015 11:21:19 INFO cloning VM...
23/Dec/2015 11:21:19 INFO cloning VM...
23/Dec/2015 11:21:19 INFO cloning VM...
23/Dec/2015 11:21:19 INFO cloning VM...
23/Dec/2015 11:21:20 INFO get_folder "first/second/third/fourth/fifth/sixth" took: 0.000211288765914 seconds
23/Dec/2015 11:21:20 INFO get_folder "decoy/inner/inner_deep_folder/" took: 0.00010475958913 seconds
23/Dec/2015 11:21:20 INFO get_folder "inner" took: 4.88406192566e-05 seconds
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00.001000
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:21:20 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:21:20 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:21:20 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:21:20 INFO Power On: True
23/Dec/2015 11:21:20 INFO Power On: True
23/Dec/2015 11:21:20 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:21:20 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:21:20 INFO Datastore: datastore
23/Dec/2015 11:21:20 INFO Datastore: datastore
23/Dec/2015 11:21:20 INFO Connecting to: <Mock name='mock.connection_details().host' id='52872720'>, As: <Mock name='mock.connection_details().username' id='52872784'>, Pwd: <Mock name='mock.connection_details().password' id='54985616'>, Port: <Mock name='mock.connection_details().port' id='54987856'>
23/Dec/2015 11:21:20 INFO Connecting to: <Mock name='mock.connection_details().host' id='52872720'>, As: <Mock name='mock.connection_details().username' id='52872784'>, Pwd: <Mock name='mock.connection_details().password' id='54985616'>, Port: <Mock name='mock.connection_details().port' id='54987856'>
23/Dec/2015 11:21:20 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='54850736'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='54851760'>
23/Dec/2015 11:21:20 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='54850736'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='54851760'>
23/Dec/2015 11:21:20 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:21:20 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:22:42 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='56029264'>:<Mock name='mock.get_connection_details().port' id='56030832'>' User: '<Mock name='mock.get_connection_details().user' id='56030768'>' Reason: TEST Exception
23/Dec/2015 11:22:42 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='56029264'>:<Mock name='mock.get_connection_details().port' id='56030832'>' User: '<Mock name='mock.get_connection_details().user' id='56030768'>' Reason: TEST Exception
23/Dec/2015 11:22:42 INFO cloning VM...
23/Dec/2015 11:22:42 INFO cloning VM...
23/Dec/2015 11:22:42 INFO cloning VM...
23/Dec/2015 11:22:42 INFO cloning VM...
23/Dec/2015 11:22:42 INFO cloning VM...
23/Dec/2015 11:22:42 INFO get_folder "first/second/third/fourth/fifth/sixth" took: 0.000256944127393 seconds
23/Dec/2015 11:22:42 INFO get_folder "decoy/inner/inner_deep_folder/" took: 0.000133780826659 seconds
23/Dec/2015 11:22:42 INFO get_folder "inner" took: 4.88406192566e-05 seconds
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:22:42 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:22:42 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:22:42 INFO Power On: True
23/Dec/2015 11:22:42 INFO Power On: True
23/Dec/2015 11:22:42 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:22:42 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:22:42 INFO Datastore: datastore
23/Dec/2015 11:22:42 INFO Datastore: datastore
23/Dec/2015 11:22:42 INFO Connecting to: <Mock name='mock.connection_details().host' id='54052368'>, As: <Mock name='mock.connection_details().username' id='54052432'>, Pwd: <Mock name='mock.connection_details().password' id='56165264'>, Port: <Mock name='mock.connection_details().port' id='56167504'>
23/Dec/2015 11:22:42 INFO Connecting to: <Mock name='mock.connection_details().host' id='54052368'>, As: <Mock name='mock.connection_details().username' id='54052432'>, Pwd: <Mock name='mock.connection_details().password' id='56165264'>, Port: <Mock name='mock.connection_details().port' id='56167504'>
23/Dec/2015 11:22:42 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='56030384'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='56031408'>
23/Dec/2015 11:22:42 INFO Folder: <Mock name='mock.getVCenterInventoryPathAttributeData().vm_folder' id='56030384'>, vCenter: <Mock name='mock.getVCenterInventoryPathAttributeData().vCenter_resource_name' id='56031408'>
23/Dec/2015 11:22:42 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:22:42 INFO Connecting to: vCenter, As: user1, Pwd: pass1
23/Dec/2015 11:23:28 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='65333360'>:<Mock name='mock.get_connection_details().port' id='65332272'>' User: '<Mock name='mock.get_connection_details().user' id='65334352'>' Reason: TEST Exception
23/Dec/2015 11:23:28 WARNING Cannot connect '<Mock name='mock.get_connection_details().host' id='65333360'>:<Mock name='mock.get_connection_details().port' id='65332272'>' User: '<Mock name='mock.get_connection_details().user' id='65334352'>' Reason: TEST Exception
23/Dec/2015 11:23:28 INFO cloning VM...
23/Dec/2015 11:23:28 INFO cloning VM...
23/Dec/2015 11:23:28 INFO cloning VM...
23/Dec/2015 11:23:28 INFO cloning VM...
23/Dec/2015 11:23:28 INFO cloning VM...
23/Dec/2015 11:23:28 INFO get_folder "first/second/third/fourth/fifth/sixth" took: 0.00147760569128 seconds
23/Dec/2015 11:23:28 INFO get_folder "decoy/inner/inner_deep_folder/" took: 0.000695801865641 seconds
23/Dec/2015 11:23:28 INFO get_folder "inner" took: 0.000226861137272 seconds
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00.001000
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:23:29 INFO find_obj_by_path took: 0:00:00
23/Dec/2015 11:23:29 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:23:29 INFO Template: test, Folder: Alex, vCenter: vCenter
23/Dec/2015 11:23:29 INFO Power On: True
23/Dec/2015 11:23:29 INFO Power On: True
23/Dec/2015 11:23:29 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:23:29 INFO Cluster: cluster1, Resource Pool: resourcePool1
23/Dec/2015 11:23:29 INFO Datastore: datastore
23/Dec/2015 11:23:29 INFO Datastore: datastore
